name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [ '14' ]

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node ${{ matrix.node }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}
        cache: 'yarn'

    - name: Install packages
      run: yarn install

    - name: Run tests
      run: yarn test

    - name: Run binary
      run: node ./bin/run
